version: '3.8'

services:

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zyzzAdmin
      - MONGO_INITDB_ROOT_PASSWORD=zyzzAdmin
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - net-menelas-auth

  express_app:
    build: ./app
    ports:
      - 8090:8090
    depends_on:
      - mongodb
    environment:
      - MONGODB=mongodb://zyzzAdmin:zyzzAdmin@mongodb
    links:
      - mongodb
    volumes:
      - ./app:/usr/src/app
    networks:
      - net-menelas-auth

networks:
  net-menelas-auth: