version: '3.8'

services:

  #mongo db
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zyzzAdmin
      - MONGO_INITDB_ROOT_PASSWORD=zyzzAdmin
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  express_app:
    build: ./app
    ports:
      - 8090:8090
    depends_on:
      - mongodb
    links:
      - mongodb