version: '3.8'

services:
  express_app:
    build: ./app
    restart: always
    ports:
      - 8090:8090
    environment:
      - MONGODB=mongodb+srv://menelas_auth:menelas_auth_password@cluster0.sm9boyv.mongodb.net/?retryWrites=true&w=majority
      - JSON_PASS=thisiszyzz
    volumes:
      - ./app:/usr/src/app
    networks:
      - net-menelas-auth

networks:
  net-menelas-auth: