name: Menelas Auth Deployment

env:
  MENELAS_AUTH_IMG_TAG: europe-southwest1-docker.pkg.dev/menelas/menelas-img-registry/menelas-auth:latest

on:
  push:
    branches:
      - master

jobs:
  build-and-push-on-gcp-registry:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install gcloud on workflow runner
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: '${{ secrets.CREDENTIALS_JSON }}'
        with:
          args: info

      - name: Authenticate on GCP
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.CREDENTIALS_JSON }}'
      
      - run: |
            gcloud auth configure-docker europe-southwest1-docker.pkg.dev

      - name: Build
        run: |
          docker build -t $MENELAS_AUTH_IMG_TAG app/

      - name: Push on registry
        run: | 
          docker push $MENELAS_AUTH_IMG_TAG
      
      - name: Deploy On Cloud run 
        run: |
          gcloud run services update menelas-auth \
          --image $MENELAS_AUTH_IMG_TAG \
          --region europe-southwest1 \
          --port 8090 \
          --ingress all \
          --max-instances 2 \
          --set-env-vars=MONGO_ROOT_USER=${{ secrets.MONGO_ROOT_USER }},JSON_PASS=${{ secrets.JSON_PASS }},MONGO_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }},MONGODB=${{ secrets.MONGO_DB_URL }}
